[package]
name = "togglebot"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
chrono = { version = "0.4.19", features = ["serde"] }
env_logger = { version = "0.8.2", default-features = false, features = ["atty", "termcolor"] }
futures-util = "0.3.12"
indoc = "1.0.3"
log = { version = "0.4.14", features = ["release_max_level_info"] }
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.61"
tokio = { version = "1.1.1", features = ["fs", "macros", "rt", "signal", "sync"] }
toml = "0.5.8"
twilight-embed-builder = "0.3.0"
twilight-gateway = "0.3.2"
twilight-http = "0.3.4"
twilight-model = "0.3.2"
twitch-irc = "2.1.0"

[dev-dependencies]
pretty_assertions = "0.6.1"

[profile.release]
lto = true
